#!/usr/bin/perl
#
# Copyright © (2006-2023) Fredrik Söderblom <fredrik@xpd.se>
#
# This file is part of Backscatter.
#
# Backscatter is free software: you can redistribute it and/or modify it under the terms of the
# GNU Affero General Public License as published by the Free Software Foundation, either 
# version 3 of the License, or (at your option) any later version.
# 
# Backscatter is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License along with 
# Backscatter. If not, see <https://www.gnu.org/licenses/>. 
#
# backscatter - monitor backscatter and pick out source ip on possibly offending hosts.
#
# backscatter creates semaphores in /var/spool/backscatter named after the offending
# source IP. report_backscatter regularly polls /var/spool/backscatter and for each
# found semaphore runs an optional nmap scan, fetches the last 100 database entries,
# generates an Afterglow graph, and writes a timestamped report and graph to
# /u/backscatter/<srcip>/ (a SAN/shared volume accessible by the SOC team).
# A local6.error syslog alert is fired for SIEM consumption via alerts.log.
#
# When       Who            What
# 2025-12-09 fredrik@xpd.se Extended WEBEX ranges - 144.196, 23.89, 62.109 and 170.72
# 2024-08-29 fredrik@xpd.se Added 144.196.128.0/19 to Webex CIDR range.
# 2023-09-20 fredrik@xpd.se Added STUN detection
# 2023-09-11 fredrik@xpd.se Updated whitelist with MSFT and Zooms latest CIDR ranges.
# 2022-02-09 fredrik@xpd.se Added Webex IP ranges.
# 2021-05-19 fredrik@xpd.se Added Zoom IP ranges.
# 2020-05-18 fredrik@xpd.se Added 13.96.0.0/13 to MSFT ranges.
# 2019-07-24 fredrik@xpd.se Added Net::CIDR support.
# 2019-01-18 fredrik@xpd.se Added whitelisting for Cloudflare.
# 2018-09-17 fredrik@xpd.se Added even more whitelisting for Akamai and MSFT.
# 2018-08-02 fredrik@xpd.se Added more whitelisting for Akamai and MSFT.
# 2017-10-09 fredrik@xpd.se Rewrote regexp to also match new syslog format from recent IOS releases.
# 2016-04-14 fredrik@xpd.se Ported to Red Hat, rewrote regexp to match rsyslog more fine grained time stamps.
# 2010-06-28 fredrik@xpd.se revamped for hashes-of-hashes implementation.
# 2009-07-21 fredrik@xpd.se save matches and whitelisting to SQL (for Afterglow graphs)
#                           implemented saving and restoring of state (SQL)
#                           implemented interrupt handling
# 2009-05-18 fredrik@xpd.se implement dampening.
# 2009-04-02 fredrik@xpd.se added temporary whitelisting of AD servers,
#                           also created foundation for afterglow integration.
# 2007-07-26 fredrik@xpd.se extended whitelist with 554/tcp and 1755/tcp.
# 2006-11-26 fredrik@xpd.se created.
#

use strict;
use warnings;
use File::Tail;
use DBI;
use Data::Dumper;
use IO::Handle;
use Net::CIDR;

my $verbose = 1;

my %hash;
my %last_seen;
my %alert;

my $line;
my $logtype;
my $proto;
my $srcip;
my $srcport;
my $dstip;
my $dstport;

my $dbh;
my $sql;
my @whitelist;
my $hits;
my $reason;

my $logfile = '/var/log/iptables.log';
my $path = '/var/spool/backscatter/';

#
# Start of functions
#

# notify report tool on new host to examine
sub report {
	my $rhash = \%hash;
	print "REPORT: " . $srcip . " (" . (keys %{$rhash->{$srcip}}) . " hits)\n" if ($verbose >= 2);
	open(FH, ">> $path/$srcip");
	close(FH);
}

sub load_whitelist {
    my @new;
    my $sth = $dbh->prepare(q{
      SELECT id, priority, reason, action, proto
        FROM whitelist_rules WHERE enabled=1 ORDER BY priority,id
    });
    $sth->execute;
    while (my $r = $sth->fetchrow_hashref) {
        $r->{cidrs} = {src=>[], dst=>[]};
        $r->{ports} = {src=>[], dst=>[]};
        my $c = $dbh->prepare(q{SELECT direction,cidr FROM whitelist_cidrs WHERE rule_id=? ORDER BY direction,cidr});
        $c->execute($r->{id});
        while (my ($d,$cidr)=$c->fetchrow_array) {
            die "invalid CIDR '$cidr' in rule $r->{id}" unless Net::CIDR::cidrvalidate($cidr);
            push @{$r->{cidrs}{$d}}, $cidr;
        }
        my $p = $dbh->prepare(q{SELECT direction,comparison,operator,operand FROM whitelist_port_predicates WHERE rule_id=? ORDER BY direction,operand});
        $p->execute($r->{id});
        while (my ($d,$cmp,$op,$operand)=$p->fetchrow_array) {
            push @{$r->{ports}{$d}}, [$cmp,$op,$operand];
        }
        push @new, $r;
    }
    @whitelist = @new; # atomic replacement after complete successful load
}

sub _port_predicate {
    my ($value,$p)=@_;
    my ($cmp,$op,$operand)=@$p;
    if ($cmp eq 'lexical') {
        return $value eq $operand if $op eq 'eq';
        return $value gt $operand if $op eq 'gt';
        return $value ge $operand if $op eq 'ge';
        return $value lt $operand if $op eq 'lt';
        return $value le $operand if $op eq 'le';
    } else {
        return $value == $operand if $op eq 'eq';
        return $value >  $operand if $op eq 'gt';
        return $value >= $operand if $op eq 'ge';
        return $value <  $operand if $op eq 'lt';
        return $value <= $operand if $op eq 'le';
    }
    die "unknown port operator $op";
}

sub whitelist_match {
    for my $r (@whitelist) {
        next if defined($r->{proto}) && uc($proto) ne uc($r->{proto});
        next if @{$r->{cidrs}{src}} && !Net::CIDR::cidrlookup($srcip,@{$r->{cidrs}{src}});
        next if @{$r->{cidrs}{dst}} && !Net::CIDR::cidrlookup($dstip,@{$r->{cidrs}{dst}});
        next if @{$r->{ports}{src}} && !grep { _port_predicate($srcport,$_) } @{$r->{ports}{src}};
        next if @{$r->{ports}{dst}} && !grep { _port_predicate($dstport,$_) } @{$r->{ports}{dst}};
        return {reason=>$r->{reason}, action=>$r->{action}, rule_id=>$r->{id}};
    }
    return;
}

sub hup_handler {
    save_state();
    eval { load_whitelist(); 1 } or warn "Whitelist reload failed; keeping previous whitelist: $@";
}

sub get_state {
	my @data;
	my $counter = 0;
	print "Restoring state - " if $verbose;
	my $sth = $dbh->prepare("SELECT srcip, dstip, hits, UNIX_TIMESTAMP(last_seen) FROM state");
	$sth->execute;
	while (@data = $sth->fetchrow_array()) {
		$hash{$data[0]}{$data[1]} = $data[2];
		$last_seen{$data[0]}{$data[1]} = $data[3];
		$counter++;
	}
	print "done ($counter state/s restored)\n" if $verbose;
}

sub save_state {
	my $counter = 0;
	if (! $dbh->ping ) {
		$dbh = $dbh->clone() or die "cannot connect to db";
	}
	print "Saving state - " if $verbose;
	my $rhash = \%hash;
	foreach my $srcip (sort keys %$rhash) {
	        foreach my $dstip (keys %{$rhash->{ $srcip }}) {
			$sql = "REPLACE INTO state (srcip, dstip, hits, last_seen) VALUES('" . $srcip . "', '" . $dstip . "', '" . $rhash->{ $srcip }{ $dstip } . "', FROM_UNIXTIME(" . ($last_seen{$srcip}{$dstip} // time()) . "))";
			$counter++;
			$dbh->do($sql);
			print "$sql\n" if ($verbose >= 10);
	        }
	}
	print "done ($counter state/s saved)\n" if $verbose;
}

sub dump_state {
	my $rhash = \%hash;
	foreach my $_srcip (sort keys %$rhash) {
		print "$_srcip: tried to reach " . (keys %{$rhash->{ $_srcip }}) . " destination/s\n";
		foreach my $_dstip (keys %{$rhash->{ $_srcip }}) {
			print "srcip: $_srcip dstip: $_dstip value: $rhash->{ $_srcip }{ $_dstip }\n";
		}
	}
}

sub periodic_save {
	alarm 0; # disable the alarm
	&save_state;
	alarm 3600; # re-arm the alarm
}

sub int_handler {
	&save_state;
	$dbh->disconnect();
	die "Interrupted, exiting.\n";
}

#
# end of functions
#

#
# Initiate DB connection
$dbh = DBI->connect('dbi:mysql:backscatter', undef, undef,
    { mysql_read_default_file  => '/home/scatter/.my.cnf',
      mysql_read_default_group => 'backscatter' }) or die "Connection Error: $DBI::errstr\n";

# Setup interrupt handlers
%SIG = (
        'INT'  => 'int_handler',
        'TERM' => 'int_handler',
        'HUP'  => 'hup_handler',
        'ALRM' => 'periodic_save',
        'USR1' => 'dump_state'
);

# Set up stdout and stderr for autoflush
STDERR->autoflush(1);
STDOUT->autoflush(1);

# Restore previous state
&get_state;

# Load whitelist from database
&load_whitelist;

# Arm the alarm
alarm 3600;

# Play the violin
print "up and running, following $logfile\n";

my $file=File::Tail->new("$logfile");
while (defined($line=$file->read))
{
	# Logs are expected to look like this:
	# 2020-06-15T14:35:02.735982+02:00 backscatter.domain.cc kernel: IN=ens666 OUT= MAC=00:50:56:82:78:XX:XX:00:XX:XX:XX:XX:XX:XX SRC=10.1.2.4 DST=2.249.46.160 LEN=364 TOS=0x00 PREC=0x00 TTL=125 ID=17291 PROTO=UDP SPT=500 DPT=500 LEN=344
	# parse line and pick out offending ip address
	$line =~ /^[ -T.:0-9]{32} [._[:alnum:]-]+ kernel: (IN=ens666) OUT= MAC=[:a-f0-9]+ SRC=([0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}) DST=([0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}) LEN=.* PROTO=([A-Z]+) SPT=([0-9]+) DPT=([0-9]+) /;

	$logtype = $1;
	$srcip = $2;
	$dstip = $3;
	$proto = $4;
	$srcport = $5;
	$dstport = $6;
	$reason = "";

	# we only parse "IN=ens666" events, skip the others.
	if (!$logtype) {
		print "IGNORE (unmatched logevent): $line" if ($verbose >= 4);
		next;
	}

	printf("%s (%s) %s %s %s %s\n", $logtype, $proto, $srcip, $srcport, $dstip, $dstport) if ($verbose >= 5);

	#
	# Filtering section
	#

        my $wl = whitelist_match();
        $reason = $wl ? $wl->{reason} : '';
        next if $wl && $wl->{action} eq 'drop_event';

	#
	# end of filters
	#

	# List reason (if any)
	if ($reason) {
		print "IGNORE ($reason): $srcip:$srcport -> $dstip:$dstport\n" if ($verbose >= 3);
		print "$line\n" if ($verbose >= 4);
	}

	#
	# Save log matches for Afterglow graphs.
	#

        $dbh->do(
                q{
                        INSERT INTO matches
                                (proto, srcip, srcport, dstip, dstport, reason)
                        VALUES (?, ?, ?, ?, ?, ?)
                },
                undef,
                $proto,
                $srcip,
                $srcport,
                $dstip,
                $dstport,
                $reason
        );
	next if $reason; # skip to next, if whitelisted.

	if (exists $hash{$srcip}{$dstip}) {
		$hash{$srcip}{$dstip} = $hash{$srcip}{$dstip} + 1;
		print "CANDIDATE (known pattern, seen " . $hash{$srcip}{$dstip} . " time/s): $srcip:$srcport -> $dstip:$dstport\n" if ($verbose >= 2);
	} else {
		$hash{$srcip}{$dstip} = 1;
		print "CANDIDATE (new pattern): $srcip:$srcport -> $dstip:$dstport\n" if ($verbose >= 2);
	}
	$last_seen{$srcip}{$dstip} = time();

	# dampening
	my $rhash = \%hash;
	for my $dst (10, 25, 50, 75, 150, 300, 600, 1200) {
		next if ((keys %{$rhash->{$srcip}}) > $dst);
		next if ((keys %{$rhash->{$srcip}}) < $dst);
		if ((keys %{$rhash->{$srcip}}) >= $dst) {		# more than $dst destinations, time to ring the bell?
			if (exists $alert{$srcip}) {
				next if ($alert{$srcip} >= $dst);	# notification already dispatched?
			}
			$alert{$srcip} = $dst;				# remember notification level and
			&report;					# .. dispatch a report.
		}
	}
}

&save_state;
$dbh->disconnect();
