# backscatter logs as local4
local4.* action(
    type="omfile"
    file="/var/log/backscatter.log"
    fileOwner="scatter"
    fileGroup="scatter"
    fileCreateMode="0600"
)

# save logs (alerts) from backscatter in "/var/log/alert.log"
local6.* action(
    type="omfile"
    file="/var/log/alert.log"
    fileOwner="scatter"
    fileGroup="scatter"
    fileCreateMode="0600"
)

# And a copy to the SOC Splunk

#local4.*,local6.*	@@siem1.domain.cc:514
#local4.*,local6.*	@@siem2.domain.cc:514

:msg, startswith, "IN=ens666" action(
    type="omfile"
    file="/var/log/iptables.log"
    fileOwner="scatter"
    fileGroup="scatter"
    fileCreateMode="0600"
)

#:msg, startswith, "IN=ens666" @@siem1.domain.cc:514
#:msg, startswith, "IN=ens666" @@siem2.domain.cc:514
& stop
